#!/usr/bin/env python3
"""基于词根词缀库生成中文助记"""
import json

JSON_PATH = "/home/cloudygirl/Anki红宝书/all_entries_v2.json"

# 前缀库 (prefix -> (英文释义, 中文释义))
PREFIXES = {
    "a": ("not/without/on/in", "不/无/在…上/在…中"),
    "ab": ("away from", "离开、偏离"),
    "abs": ("away from", "离开"),
    "ac": ("to/toward", "向、朝着"),
    "ad": ("to/toward", "向、朝着、添加"),
    "af": ("to/toward", "向"),
    "ag": ("to/toward", "向"),
    "al": ("to/toward/all", "向/全"),
    "am": ("to/love", "向/爱"),
    "an": ("not/without", "不/无"),
    "ana": ("up/back", "向上、向后"),
    "ante": ("before", "在…之前"),
    "anti": ("against/opposite", "反对、对抗、相反"),
    "ap": ("to/toward", "向"),
    "apo": ("away from", "离开"),
    "ar": ("to/toward", "向"),
    "as": ("to/toward", "向"),
    "at": ("to/toward", "向"),
    "auto": ("self", "自己、自动"),
    "be": ("make/cause to be", "使成为、在…周围"),
    "bene": ("good/well", "好、善"),
    "bi": ("two/twice", "二、双、两"),
    "bio": ("life", "生命、生物"),
    "by": ("near/side", "旁边、次要"),
    "cata": ("down", "向下"),
    "cent": ("hundred", "百"),
    "circum": ("around", "周围、环绕"),
    "co": ("together/with", "共同、一起"),
    "col": ("together/with", "共同、一起"),
    "com": ("together/with", "共同、一起"),
    "con": ("together/with", "共同、一起"),
    "contra": ("against", "反对、对抗"),
    "contro": ("against", "反对"),
    "cor": ("together/with", "共同、一起"),
    "counter": ("against/opposite", "反对、相反"),
    "de": ("down/away/remove/opposite", "向下、离开、去除、相反"),
    "deca": ("ten", "十"),
    "deci": ("tenth", "十分之一"),
    "demi": ("half", "半"),
    "di": ("two/apart/through", "二、分开、穿过"),
    "dia": ("through/across", "穿过、在…之间"),
    "dif": ("apart/not", "分开、不"),
    "dis": ("apart/not/opposite", "分开、不、相反"),
    "du": ("two", "二、双"),
    "dys": ("bad/hard", "坏、困难"),
    "e": ("out/from", "出、外、来自"),
    "ec": ("out", "出"),
    "ef": ("out", "出"),
    "em": ("in/into/make", "进入/使"),
    "en": ("in/into/make", "进入/使"),
    "endo": ("inside", "内部"),
    "epi": ("upon/over", "在…上、在…外"),
    "equi": ("equal", "相等、平等"),
    "eu": ("good/well", "好、良好"),
    "ex": ("out/former", "出、外、前任"),
    "exo": ("outside", "外部"),
    "extra": ("outside/beyond", "超出、额外"),
    "for": ("away/against/before", "离开、反对、前"),
    "fore": ("before/front", "前、预先"),
    "forth": ("forward", "向前"),
    "hemi": ("half", "半"),
    "hetero": ("different", "异、不同"),
    "homo": ("same", "同、相同"),
    "hyper": ("over/excessive", "超过、过度"),
    "hypo": ("under/below", "在…下、低于"),
    "il": ("not", "不、无"),
    "im": ("not/into", "不/进入"),
    "in": ("not/into/within", "不/进入/内部"),
    "infra": ("below", "在…下、低"),
    "inter": ("between/among", "在…之间、相互"),
    "intra": ("within/inside", "在内"),
    "intro": ("into/inward", "向内"),
    "ir": ("not", "不"),
    "iso": ("equal", "相等"),
    "kilo": ("thousand", "千"),
    "macro": ("large", "大、宏观"),
    "mal": ("bad/wrong", "坏、错误"),
    "meta": ("beyond/change", "超越、变化"),
    "micro": ("small", "小、微观"),
    "mid": ("middle", "中间"),
    "milli": ("thousandth", "千分之一、毫"),
    "mini": ("small", "小"),
    "mis": ("wrong/badly", "错误、坏"),
    "mono": ("one/single", "一、单"),
    "multi": ("many", "多"),
    "neo": ("new", "新"),
    "non": ("not", "不、非"),
    "ob": ("against/toward", "反对、朝向"),
    "oct": ("eight", "八"),
    "omni": ("all", "全、全部"),
    "out": ("beyond/outside", "超过、外部"),
    "over": ("above/excessive", "超过、过度"),
    "pan": ("all", "全、泛"),
    "para": ("beside/beyond/against", "旁、超、反对"),
    "per": ("through/thoroughly", "穿过、彻底"),
    "peri": ("around", "周围"),
    "phil": ("love", "爱"),
    "phob": ("fear", "恐惧"),
    "phon": ("sound", "声音"),
    "photo": ("light", "光"),
    "poly": ("many", "多"),
    "post": ("after/behind", "之后、后面"),
    "pre": ("before", "之前、预先"),
    "pro": ("forward/for/before", "向前、赞成、之前"),
    "proto": ("first", "第一、原始"),
    "pseudo": ("false", "假、伪"),
    "psycho": ("mind/soul", "心理、灵魂"),
    "quad": ("four", "四"),
    "quasi": ("seemingly/almost", "类似、准"),
    "re": ("again/back", "再次、向后、回"),
    "retro": ("backward", "向后、回溯"),
    "se": ("apart/away", "分开、离开"),
    "self": ("self", "自己"),
    "semi": ("half", "半"),
    "sept": ("seven", "七"),
    "sex": ("six", "六"),
    "step": ("related by remarriage", "继、后"),
    "sub": ("under/below", "在…下、次、亚"),
    "suc": ("under", "在…下"),
    "suf": ("under", "在…下"),
    "sug": ("under", "在…下"),
    "sum": ("under/highest", "在…下/最高"),
    "sup": ("under/above", "在…下/上"),
    "super": ("above/over/excellent", "在…上、超级、极其"),
    "sur": ("over/above", "在…上、超过"),
    "sus": ("under/up from under", "在…下、从下向上"),
    "sym": ("together/same", "共同、相同"),
    "syn": ("together/same", "共同、相同"),
    "tele": ("far/distant", "远、远程"),
    "tetra": ("four", "四"),
    "therm": ("heat", "热"),
    "trans": ("across/beyond/change", "跨、超越、变化"),
    "tri": ("three", "三"),
    "twi": ("two", "二"),
    "ultra": ("beyond/extreme", "超越、极端"),
    "un": ("not/opposite", "不、相反"),
    "under": ("below/insufficient", "在…下、不足"),
    "uni": ("one/single", "一、单、统一"),
    "up": ("upward/higher", "向上、升高"),
    "vice": ("deputy/in place of", "副、代"),
    "with": ("against/back", "反对、向后"),
}

# 词根库 (root -> (英文释义, 中文释义))
ROOTS = {
    "act": ("do/drive", "做、行动、驱动"),
    "ag": ("do/drive", "做、行动、驱动"),
    "agon": ("struggle", "斗争、竞争"),
    "agr": ("field/land", "田地、农业"),
    "ali": ("other/else", "其他、别"),
    "alter": ("other/change", "其他、改变"),
    "am": ("love/like", "爱、喜欢"),
    "ambul": ("walk", "走、行走"),
    "anim": ("life/spirit/mind", "生命、精神、心智"),
    "ann": ("year", "年"),
    "anthrop": ("human", "人类"),
    "apt": ("fit/suitable", "适合、合适"),
    "aqua": ("water", "水"),
    "arch": ("rule/chief/ancient", "统治、首领、古老"),
    "arm": ("weapon", "武器"),
    "art": ("skill/craft", "技艺、艺术"),
    "aster": ("star", "星"),
    "aud": ("hear/listen", "听"),
    "aug": ("increase", "增加"),
    "avi": ("bird/fly", "鸟、飞"),
    "ball": ("throw", "投、掷"),
    "band": ("bind/tie", "绑、束缚"),
    "bar": ("bar/obstacle", "棒、障碍"),
    "bas": ("low/foundation", "低、基础"),
    "bat": ("beat", "打、击"),
    "bell": ("war", "战争"),
    "biblio": ("book", "书"),
    "brev": ("short", "短"),
    "cad": ("fall", "落、降"),
    "camp": ("field", "田野、营地"),
    "cand": ("white/shine", "白、发光"),
    "cant": ("sing", "唱"),
    "cap": ("head/take/hold", "头、拿、抓、容量"),
    "car": ("dear/costly", "昂贵、珍爱"),
    "card": ("heart", "心"),
    "carn": ("flesh/meat", "肉"),
    "cast": ("throw", "投、掷"),
    "caus": ("reason/cause", "原因、理由"),
    "cav": ("hollow", "空、洞"),
    "cede": ("go/yield", "走、让步"),
    "ceive": ("take/hold", "拿、抓"),
    "celer": ("swift/fast", "快、迅速"),
    "cent": ("hundred", "百"),
    "centr": ("center", "中心"),
    "cept": ("take/hold", "拿、抓、接受"),
    "cern": ("separate/disting", "分离、辨别"),
    "cert": ("sure/certain", "确定、确信"),
    "chrom": ("color", "颜色"),
    "chron": ("time", "时间"),
    "cide": ("kill/cut", "杀、切"),
    "cip": ("take/hold", "拿、抓"),
    "circ": ("circle/ring", "圆、环"),
    "cis": ("cut", "切、割"),
    "cit": ("call/summon", "呼喊、召集"),
    "civ": ("citizen/city", "公民、城市"),
    "claim": ("shout/call out", "喊、声称"),
    "clar": ("clear/bright", "清楚、明亮"),
    "clin": ("lean/bend", "倾斜、倚靠"),
    "clud": ("shut/close", "关闭、结束"),
    "cogn": ("know/learn", "知道、认识"),
    "cord": ("heart", "心"),
    "corp": ("body", "身体、团体"),
    "cosm": ("universe/order", "宇宙、秩序"),
    "cracy": ("rule/power", "统治、权力"),
    "cre": ("make/create", "制造、创造"),
    "cred": ("believe/trust", "相信、信任"),
    "cresc": ("grow", "生长"),
    "crit": ("judge/decide", "判断、决定"),
    "cult": ("till/care", "耕作、培养"),
    "cur": ("care/run/flow", "关心/跑/流"),
    "curs": ("run/flow", "跑、流"),
    "cycl": ("circle/wheel", "圆、轮、循环"),
    "dat": ("give", "给、提供"),
    "deb": ("owe", "欠"),
    "dec": ("ten/proper", "十/合适"),
    "dem": ("people", "人民"),
    "dent": ("tooth", "牙"),
    "derm": ("skin", "皮肤"),
    "dic": ("say/speak/declare", "说、讲、宣告"),
    "digit": ("finger/number", "手指、数字"),
    "div": ("divide/separate", "分、分开"),
    "doc": ("teach", "教"),
    "dom": ("rule/house/home", "统治、家"),
    "don": ("give", "给予"),
    "dorm": ("sleep", "睡眠"),
    "dox": ("opinion/belief", "观点、教义"),
    "duc": ("lead/bring", "引导、带来"),
    "dur": ("hard/last", "坚硬、持续"),
    "dyn": ("power/force", "力量、动力"),
    "eco": ("house/environment", "家、环境"),
    "ego": ("self/I", "自己、我"),
    "electr": ("electric/amber", "电"),
    "enn": ("year", "年"),
    "equ": ("equal/even", "相等、平等"),
    "erg": ("work/energy", "工作、能量"),
    "err": ("wander/mistake", "漫游、错误"),
    "ess": ("be/exist", "存在、是"),
    "ethn": ("nation/race", "民族、种族"),
    "fac": ("make/do/face", "做/脸/面"),
    "fall": ("deceive/fail/false", "欺骗、失败、假"),
    "fam": ("family/reputation", "家庭、名声"),
    "fess": ("speak/declare", "说、声明"),
    "fest": ("feast/festival", "节日、宴会"),
    "fict": ("make/invent", "制造、虚构"),
    "fid": ("faith/trust", "信仰、信任"),
    "fin": ("end/boundary", "结束、界限"),
    "firm": ("strong/steady", "坚固、稳定"),
    "fix": ("fasten/attach", "固定、安装"),
    "flam": ("flame/fire", "火焰"),
    "flat": ("blow", "吹"),
    "flect": ("bend", "弯曲"),
    "flict": ("strike", "打击"),
    "flor": ("flower", "花"),
    "flu": ("flow", "流"),
    "form": ("shape/form", "形状、形式"),
    "fort": ("strong", "强、力量"),
    "fract": ("break", "打破、碎裂"),
    "frag": ("break", "打破"),
    "fug": ("flee", "逃、散"),
    "fus": ("pour/melt", "流、灌、融化"),
    "gam": ("marriage", "婚姻、结合"),
    "gen": ("birth/kind/race", "出生、种类、种族"),
    "geo": ("earth/ground", "地、地球"),
    "gest": ("carry/bear", "运、承载"),
    "gnos": ("know", "知道"),
    "grad": ("step/walk/degree", "步、走、等级"),
    "gram": ("write/letter", "写、文字"),
    "graph": ("write/draw", "写、画"),
    "grat": ("please/thank", "高兴、感谢"),
    "grav": ("heavy/serious", "重、严肃"),
    "greg": ("flock/gather", "群、聚集"),
    "gress": ("step/go/walk", "步、走"),
    "habit": ("have/hold/live", "有/居住/习惯"),
    "her": ("stick/attach", "粘、附着"),
    "here": ("stick/attach", "粘、附着"),
    "hibit": ("hold/have", "持有、把持"),
    "horr": ("tremble/bristle", "发抖、恐惧"),
    "hum": ("earth/human", "地/人"),
    "hydr": ("water", "水"),
    "hypn": ("sleep", "睡眠"),
    "icon": ("image/idol", "图像、偶像"),
    "ide": ("idea/thought", "思想、观念"),
    "imit": ("copy/likeness", "模仿、相似"),
    "insul": ("island", "岛"),
    "integr": ("whole/complete", "完整"),
    "it": ("go/walk", "走、行"),
    "ject": ("throw/cast", "投、掷、抛"),
    "join": ("connect", "连接、加入"),
    "journ": ("day", "日、天"),
    "jud": ("judge/law", "判断、法律"),
    "junct": ("join/connect", "连接"),
    "jur": ("swear/law", "发誓、法律"),
    "just": ("right/lawful", "公正、法律"),
    "juven": ("young", "年轻"),
    "labor": ("work/toil", "劳动、工作"),
    "laps": ("slip/fall", "滑、落"),
    "lat": ("carry/bring/wide", "携带/宽"),
    "later": ("side", "边、侧面"),
    "lav": ("wash", "洗"),
    "law": ("law", "法律"),
    "lax": ("loose", "松"),
    "lect": ("choose/gather/read", "选择、收集、读"),
    "leg": ("law/read/choose", "法律、读、选"),
    "lev": ("light/raise", "轻、升起"),
    "liber": ("free", "自由"),
    "lig": ("bind/tie", "绑、束缚"),
    "limit": ("boundary", "界限、限制"),
    "line": ("line", "线"),
    "lingu": ("tongue/language", "舌、语言"),
    "lith": ("stone", "石"),
    "liter": ("letter", "文字、字母"),
    "lith": ("stone", "石头"),
    "loc": ("place", "地方、位置"),
    "log": ("speech/word/reason", "说话、词、理性"),
    "long": ("long", "长"),
    "loqu": ("speak", "说"),
    "luc": ("light", "光、明亮"),
    "lud": ("play", "玩、游戏"),
    "lumin": ("light", "光"),
    "lun": ("moon", "月"),
    "magn": ("great/large", "大、伟大"),
    "mand": ("order/command", "命令、委托"),
    "man": ("hand/stay", "手/停留"),
    "mar": ("sea", "海"),
    "mater": ("mother", "母"),
    "maxim": ("greatest", "最大"),
    "mechan": ("machine", "机器、机械"),
    "medi": ("middle", "中间"),
    "medic": ("heal", "治疗、医药"),
    "memor": ("remember", "记忆"),
    "mens": ("measure", "测量"),
    "ment": ("mind/think", "心智、思考"),
    "merc": ("trade/pay", "贸易、报酬"),
    "merg": ("sink/dip", "沉、浸"),
    "meter": ("measure", "测量、计量"),
    "migr": ("wander/move", "迁移"),
    "milit": ("soldier", "士兵、军事"),
    "min": ("small/less/project", "小、少、突出"),
    "mir": ("wonder/look", "惊奇、看"),
    "miss": ("send/let go", "送、放、发射"),
    "mit": ("send/let go", "送、放"),
    "mix": ("mix", "混合"),
    "mob": ("move", "移动"),
    "mod": ("measure/manner", "方式、尺度、模式"),
    "mon": ("warn/alone/mind", "警告/单一/心"),
    "morph": ("form/shape", "形态"),
    "mort": ("death", "死"),
    "mot": ("move", "移动"),
    "mount": ("mountain/rise", "山、上升"),
    "mov": ("move", "移动"),
    "mun": ("service/duty/wall", "服务、义务、墙"),
    "mus": ("muse/art", "缪斯、艺术"),
    "mut": ("change", "改变、变换"),
    "myth": ("story", "神话、故事"),
    "narr": ("tell", "讲述"),
    "nas": ("born", "出生"),
    "nat": ("born", "出生、天生"),
    "naut": ("sailor/ship", "航海、船"),
    "nav": ("ship", "船"),
    "nect": ("bind/connect", "连接、绑定"),
    "neg": ("deny", "否定"),
    "neur": ("nerve", "神经"),
    "neutr": ("neither", "中立、两者都不"),
    "nihil": ("nothing", "无、虚无"),
    "noct": ("night", "夜"),
    "nom": ("name/law", "名字、法律"),
    "norm": ("rule/normal", "规则、正常"),
    "not": ("know/mark/note", "知道、标记"),
    "nov": ("new", "新"),
    "nox": ("harm", "伤害"),
    "numer": ("number", "数"),
    "nunci": ("announce/tell", "宣布、告知"),
    "nutri": ("nourish", "营养、滋养"),
    "onym": ("name", "名字"),
    "oper": ("work", "工作、操作"),
    "opt": ("choose/best/eye", "选择/最好/眼"),
    "ora": ("speak/pray", "说、祷告"),
    "order": ("order/arrange", "秩序、安排"),
    "organ": ("instrument/organ", "工具、器官、组织"),
    "ori": ("rise/begin", "升起、开始"),
    "orn": ("decorate", "装饰"),
    "ortho": ("straight/correct", "直、正确"),
    "paci": ("peace", "和平、平静"),
    "pact": ("fasten/agree", "固定、同意"),
    "par": ("equal/prepare/appear", "相等/准备/出现"),
    "part": ("part/divide", "部分、分开"),
    "pass": ("pass/go through/step", "通过/步"),
    "pater": ("father", "父"),
    "path": ("feeling/suffer", "感情、痛苦"),
    "patri": ("father/fatherland", "父、祖国"),
    "ped": ("foot/child", "足、儿童"),
    "pel": ("drive/push", "驱赶、推"),
    "pen": ("punish/almost", "惩罚/几乎"),
    "pend": ("hang/weigh/pay", "悬挂、称重、支付"),
    "pens": ("hang/weigh/pay", "悬挂、称重、支付"),
    "peri": ("try/test", "尝试、试验"),
    "pet": ("seek/rush at", "寻求、追求"),
    "phil": ("love", "爱"),
    "phob": ("fear", "恐惧"),
    "phon": ("sound/voice", "声音"),
    "photo": ("light", "光"),
    "pict": ("paint", "画、描绘"),
    "plac": ("please/calm/place", "取悦/平静/放置"),
    "plaud": ("clap/applaud", "拍手、鼓掌"),
    "ple": ("fill/full", "充满、满"),
    "plex": ("fold/weave", "折叠、编织"),
    "plic": ("fold", "折叠"),
    "plor": ("cry out/weep", "喊、哭"),
    "ploy": ("fold/use", "折叠、使用"),
    "plumb": ("lead", "铅"),
    "pneum": ("breath/lung", "呼吸、肺"),
    "point": ("point/pierce", "点、刺"),
    "polis": ("city", "城市"),
    "polit": ("city/state", "城市、国家、政治"),
    "pon": ("put/place", "放、置"),
    "popul": ("people", "人民、民众"),
    "port": ("carry/gate", "携带、运、门"),
    "pos": ("put/place", "放、置"),
    "poss": ("able/power", "能、能力"),
    "pot": ("power/ability", "能力、力量"),
    "prec": ("pray/request/price", "祈祷/请求/价值"),
    "pred": ("prey/before", "捕食/前"),
    "press": ("press/push", "压、挤"),
    "prim": ("first", "第一、最初"),
    "pris": ("take/seize", "抓、拿"),
    "priv": ("private/separate", "私下、分离"),
    "prob": ("test/prove", "检验、证明"),
    "proper": ("one's own/appropriate", "自己的、恰当的"),
    "psych": ("mind/soul", "心灵、精神"),
    "publ": ("people/public", "公众"),
    "puls": ("drive/push/beat", "驱动、推、击"),
    "punct": ("point/prick", "点、刺"),
    "pur": ("pure/clean", "纯、净"),
    "put": ("think/consider", "思考、认为"),
    "pyr": ("fire", "火"),
    "qual": ("quality/nature", "性质、品质"),
    "quer": ("ask/seek/complain", "问、寻求、抱怨"),
    "quest": ("ask/seek", "问、寻求"),
    "quiet": ("rest/calm", "安静"),
    "quit": ("free/release", "自由、释放"),
    "radi": ("ray/root", "射线、根"),
    "rap": ("seize/snatch", "抓、夺"),
    "ras": ("scrape/shave", "刮、擦"),
    "rat": ("reason/calculate", "推理、计算"),
    "rect": ("right/straight/rule", "正确、直、统治"),
    "reg": ("rule/guide/king", "统治、指导、王"),
    "rid": ("laugh", "笑"),
    "rig": ("stiff/straight", "僵硬、直"),
    "riv": ("stream/river", "河、流"),
    "rob": ("strong/red", "力量/红"),
    "rod": ("gnaw", "咬、啃"),
    "rog": ("ask", "问、要求"),
    "rot": ("wheel/turn", "轮、转"),
    "rupt": ("break/burst", "破、断裂"),
    "sacr": ("sacred/holy", "神圣"),
    "sal": ("salt/jump", "盐/跳"),
    "san": ("health/heal", "健康"),
    "sanc": ("sacred/holy", "神圣"),
    "sangui": ("blood", "血"),
    "sat": ("enough/full", "足够、满"),
    "scend": ("climb", "爬、攀登"),
    "sci": ("know", "知、了解"),
    "scope": ("see/look", "看、观察"),
    "scrib": ("write", "写"),
    "script": ("write", "写"),
    "sec": ("follow", "跟随"),
    "sect": ("cut", "切、割"),
    "sed": ("sit/settle/calm", "坐、安顿、平静"),
    "sembl": ("like/similar", "相似"),
    "semin": ("seed", "种子"),
    "sen": ("old/feel/perceive", "老/感觉/感知"),
    "sens": ("feel/perceive", "感觉、察觉"),
    "sequ": ("follow", "跟随"),
    "sert": ("join/assert", "加入、断言"),
    "serv": ("serve/keep/watch", "服务、保持、看"),
    "sess": ("sit", "坐"),
    "sign": ("sign/mark", "记号、标志"),
    "simil": ("like/same", "相似、相同"),
    "sinu": ("curve/bend", "弯曲"),
    "sist": ("stand/place", "站立、放置"),
    "soci": ("companion/ally", "同伴、社会"),
    "sol": ("alone/sun", "单独/太阳"),
    "solv": ("loosen/free", "解开、解放"),
    "somn": ("sleep", "睡眠"),
    "son": ("sound", "声音"),
    "soph": ("wisdom", "智慧"),
    "sort": ("kind/lot", "种类、命运"),
    "spec": ("look/see", "看"),
    "spher": ("ball/sphere", "球"),
    "spir": ("breathe/spirit", "呼吸、精神"),
    "splend": ("shine", "发光、辉煌"),
    "spond": ("pledge/promise", "保证、承诺"),
    "st": ("stand", "站、立"),
    "stall": ("place/stand", "放置、使停止"),
    "stan": ("stand", "站、立"),
    "stat": ("stand/state/station", "站/状态/站"),
    "stell": ("star", "星"),
    "stimul": ("goad/prick", "刺激"),
    "stinct": ("prick/mark", "刺、标记"),
    "stitut": ("set up/establish", "建立、设立"),
    "string": ("bind/draw tight", "绑、拉紧"),
    "struct": ("build", "建造、构建"),
    "suad": ("advise/urge", "劝说、催促"),
    "sum": ("highest/total/take", "最高/总/拿"),
    "surg": ("rise", "升起、上升"),
    "tact": ("touch", "接触、触摸"),
    "tail": ("cut", "切、割"),
    "tang": ("touch", "触摸"),
    "techn": ("skill/art", "技术、技艺"),
    "tect": ("cover", "盖、遮蔽"),
    "temper": ("mix/moderate", "混合、调节"),
    "tempor": ("time", "时间"),
    "tempt": ("try/test", "尝试、考验"),
    "tend": ("stretch/strive/tend", "伸展、倾向、趋向"),
    "ten": ("hold/stretch", "拿、握、伸展"),
    "ter": ("earth", "地、地球"),
    "term": ("end/boundary", "终点、界限"),
    "terr": ("earth/frighten", "地/恐吓"),
    "test": ("witness/evidence", "证明、证据"),
    "text": ("weave", "编织、文本"),
    "the": ("god/put", "神、放置"),
    "therm": ("heat", "热"),
    "tom": ("cut", "切、割"),
    "ton": ("tone/sound", "音"),
    "tort": ("twist", "扭、弯曲"),
    "tox": ("poison", "毒"),
    "tract": ("draw/pull", "拉、拖、引"),
    "trib": ("give/pay", "给予、分配"),
    "trop": ("turn/change", "转、变化"),
    "trud": ("thrust/push", "推"),
    "turb": ("disturb/confuse", "扰乱、混乱"),
    "typ": ("type/model", "类型、模型"),
    "umbr": ("shadow", "阴影"),
    "un": ("one", "一、单"),
    "und": ("wave/overflow", "波浪/溢出"),
    "urb": ("city", "城市"),
    "us": ("use", "用、使用"),
    "vac": ("empty", "空"),
    "vad": ("go", "走、去"),
    "vag": ("wander", "漫游、漂泊"),
    "val": ("worth/strong", "价值、强壮"),
    "van": ("empty/vain", "空、徒劳"),
    "vari": ("change/different", "变化、不同"),
    "ven": ("come", "来"),
    "vent": ("come/wind", "来/风"),
    "ver": ("true", "真实"),
    "verb": ("word", "词、言语"),
    "vers": ("turn/change", "转、变化"),
    "vert": ("turn/change", "转、变化"),
    "vest": ("clothing", "衣服"),
    "vi": ("way/road", "路、道路"),
    "vict": ("conquer", "征服、胜利"),
    "vid": ("see", "看"),
    "vig": ("lively/strong", "活力、强"),
    "vill": ("farm/village", "农庄、村庄"),
    "vinc": ("conquer", "征服"),
    "vir": ("man/poison", "男人/毒"),
    "vis": ("see", "看"),
    "vit": ("life", "生命"),
    "viv": ("live/alive", "活、生命"),
    "voc": ("call/voice", "呼喊、声音"),
    "vol": ("will/fly/roll", "意志、意愿/飞/滚"),
    "volu": ("roll/turn", "滚、转"),
    "volv": ("roll/turn", "滚、转"),
    "vor": ("eat", "吃"),
    "vot": ("vow/wish", "发誓、愿望"),
    "vulg": ("common people", "民众、普通"),
    "vuln": ("wound", "伤口"),
    "zo": ("animal", "动物"),
}

# 后缀库 (suffix -> (英文释义, 中文释义))
SUFFIXES = {
    "able": ("able/capable", "能…的、可…的"),
    "ible": ("able/capable", "能…的、可…的"),
    "acy": ("state/quality", "状态、性质"),
    "age": ("state/act/result", "状态/行为/结果"),
    "al": ("pertaining to", "…的、关于…的"),
    "ance": ("state/quality/act", "状态、性质、行为"),
    "ancy": ("state/quality", "状态、性质"),
    "ant": ("one who/that which", "…的人/物"),
    "ar": ("pertaining to/one who", "…的/…的人"),
    "ard": ("one who does excessively", "过于…的人"),
    "ary": ("relating to/place for", "关于…的/…的场所"),
    "ate": ("to make/having", "使…、具有…的"),
    "ation": ("act/process/result", "行为、过程、结果"),
    "dom": ("state/condition/domain", "状态、领域"),
    "ed": ("having/past", "具有…的/过去"),
    "ee": ("one who receives", "被…的人、受动者"),
    "eer": ("one who does", "从事…的人"),
    "en": ("made of/to make", "由…制成/使成为"),
    "ence": ("state/quality/act", "状态、性质、行为"),
    "ency": ("state/quality", "状态、性质"),
    "ent": ("one who/that which", "…的人/物、…的"),
    "er": ("one who/comparative", "…的人/更…"),
    "ern": ("direction/pertaining to", "方向/…的"),
    "ery": ("place/quality/art", "场所/性质/技艺"),
    "ese": ("pertaining to/native of", "…人的、…语的"),
    "ess": ("female", "女、雌性"),
    "est": ("most", "最…"),
    "fold": ("times", "…倍"),
    "ful": ("full of/characterized by", "充满…的"),
    "fy": ("to make/to cause", "使…、使…化"),
    "hood": ("state/condition", "状态、身份、时期"),
    "ial": ("pertaining to", "…的、关于…的"),
    "ian": ("pertaining to/one who", "…的/…的人"),
    "ic": ("pertaining to/like", "…的、…似的"),
    "ical": ("pertaining to", "…的"),
    "ice": ("quality/state", "性质、状态"),
    "id": ("pertaining to/state", "…的/状态"),
    "ier": ("one who", "…的人"),
    "ile": ("pertaining to/capable", "…的/能…的"),
    "ing": ("action/process/result", "行为、过程、结果"),
    "ion": ("act/process/result", "行为、过程、结果"),
    "ious": ("full of/having", "充满…的"),
    "ise": ("to make/to do", "使…、使…化"),
    "ish": ("like/pertaining to", "似…的、…般的"),
    "ism": ("doctrine/system/act", "主义、制度、行为"),
    "ist": ("one who practices", "从事…的人、…家"),
    "ite": ("native of/product", "…的产物/…人"),
    "ity": ("state/quality", "状态、性质"),
    "ive": ("tending to/having nature of", "有…倾向的/有…性质的"),
    "ization": ("act/process of making", "使…化的过程"),
    "ize": ("to make/to cause", "使…化、使成为"),
    "less": ("without/lacking", "无…的、不…的"),
    "like": ("similar to", "像…的"),
    "ling": ("small/young", "小、幼"),
    "logy": ("study/science of", "…学、…论"),
    "ly": ("like/in manner of", "像…地/每…的"),
    "ment": ("act/result/state", "行为、结果、状态"),
    "most": ("most", "最…"),
    "ness": ("state/quality", "状态、性质"),
    "or": ("one who/that which", "…的人/物"),
    "ory": ("relating to/place for", "关于…的/…场所"),
    "ous": ("full of/having", "充满…的/有…性质的"),
    "proof": ("resistant to", "防…的"),
    "ry": ("place/act/collection", "场所/行为/集合"),
    "ship": ("state/condition/skill", "状态/身份/技能"),
    "some": ("characterized by/tending", "有…倾向的"),
    "th": ("state/quality/act", "状态/性质/行为/第…"),
    "tion": ("act/process/result", "行为、过程、结果"),
    "tious": ("having quality of", "有…性质的"),
    "tive": ("having quality of", "有…性质的"),
    "tude": ("state/quality", "状态、性质"),
    "ty": ("state/quality", "状态、性质"),
    "ure": ("act/process/result", "行为、过程、结果"),
    "ward": ("in direction of", "向…方向"),
    "wards": ("in direction of", "向…方向"),
    "ways": ("in direction of", "向…方向"),
    "wise": ("in manner/direction", "以…方式/朝向"),
    "y": ("characterized by/full of", "…的/充满…的"),
}

def decompose(word: str) -> list | None:
    """贪心分解单词为(前缀)+词根+后缀，返回 [(部分, cn_cn), ...]"""
    result = []
    remaining = word.lower()
    
    # 先移除常见的词尾变化
    # -ing, -ed 结尾
    if remaining.endswith("ing") and len(remaining) > 4:
        # 检查是否为进行时
        base = remaining[:-3]
        if base + "e" == remaining[:-3] + "e":
            pass  # 可能是去 e 加 ing
        result.append(("ing", "行为/过程/进行,表进行"))
        remaining = base
        # 去除后再分解
    elif remaining.endswith("ed") and len(remaining) > 4:
        result.append(("ed", "过去/被动,表过去"))
        remaining = remaining[:-2]
    
    # 先匹配前缀（从长到短）
    matched_prefix = True
    while matched_prefix and remaining:
        matched_prefix = False
        for pfx in sorted(PREFIXES.keys(), key=len, reverse=True):
            if remaining.startswith(pfx) and len(remaining) - len(pfx) >= 2:
                result.append((pfx, PREFIXES[pfx][1]))
                remaining = remaining[len(pfx):]
                matched_prefix = True
                break
    
    # 匹配后缀（从长到短），从末尾去掉
    matched_suffix = True
    while matched_suffix and remaining:
        matched_suffix = False
        for sfx in sorted(SUFFIXES.keys(), key=len, reverse=True):
            if remaining.endswith(sfx) and len(remaining) - len(sfx) >= 2 and sfx not in ("ing", "ed"):
                result.append((sfx, SUFFIXES[sfx][1]))
                remaining = remaining[:-len(sfx)]
                matched_suffix = True
                break
    
    # 剩余部分尝试匹配词根
    if remaining and len(remaining) >= 2:
        # 从长到短匹配
        best_root = None
        for root in sorted(ROOTS.keys(), key=len, reverse=True):
            if root == remaining:
                best_root = root
                break
            if root in remaining and len(root) >= 3:
                best_root = root
                break
        if best_root is None and len(remaining) >= 2:
            # 找包含关系
            for root in sorted(ROOTS.keys(), key=len, reverse=True):
                if root in remaining:
                    best_root = root
                    break
        
        if best_root:
            result.append((best_root, ROOTS[best_root][1]))
        elif remaining:
            result.append((remaining, remaining))

    return result if result else None


def generate_mnemonic(word: str, meaning_hint: str = "") -> str | None:
    """生成中文助记"""
    parts = decompose(word)
    if not parts or len(parts) < 2:
        return None

    # 构建助记字符串: part1（释义）十 part2（释义）一→中文意思提示
    segments = []
    for part_text, part_cn in parts:
        if part_text == part_cn:
            # 没匹配到词根库，用英文原样
            cnt = min(8, len(part_cn))
            # 提取释义中匹配的中文
            if meaning_hint:
                segments.append(f"{part_text}（{part_cn[:8]}）")
            else:
                continue
        else:
            segments.append(f"{part_text}（{part_cn}）")

    if not segments:
        return None

    # 添加连接符
    mnem = "十".join(segments)
    
    # 从原有释义中提取简短中文提示
    hint = ""
    if meaning_hint:
        # 取释义的前几个中文字符
        clean = meaning_hint
        # 去掉英文词性标注
        import re
        clean = re.sub(r'^[a-z]+\.\s*', '', clean.strip())
        clean = re.sub(r'^[a-z]+\s*', '', clean.strip())
        if clean:
            hint = clean[:20]  # 最多20个中文字
    if hint:
        mnem += f"→{hint}"
    
    return mnem


if __name__ == "__main__":
    with open(JSON_PATH) as f:
        entries = json.load(f)
    
    no_mnem = [e for e in entries if not e.get('mnemonic', '').strip()]
    print(f"需生成助记: {len(no_mnem)}")
    
    ok = 0
    skip = 0
    for entry in no_mnem:
        word = entry['word']
        meaning = entry.get('meaning', '')
        mnem = generate_mnemonic(word, meaning)
        if mnem:
            entry['mnemonic'] = mnem
            ok += 1
        else:
            skip += 1
    
    with open(JSON_PATH, 'w') as f:
        json.dump(entries, f, ensure_ascii=False, indent=1)
    
    print(f"生成: {ok}  跳过(单音节/无法分解): {skip}")
    
    # 显示样例
    samples = [e for e in entries if e.get('mnemonic') and e['mnemonic'].startswith('re')][:3]
    for e in samples:
        print(f"\n  {e['word']}: {e['mnemonic'][:120]}")
